### ISSUE TITLE
FACTS to display

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#10]
Can I select what facts I want displayed?  I thought I could in the old admin system but cant see it in the new....

We probably do not want to display immigration, occupation, religion, source notes etc.... (our users have requested that just basic details are shown).  I know I asked about immigration earlier but we just checked our FAQ that users get and we have restricted the facts displayed.

**Comment by fisharebest** [comment]
Do this via the privacy settings.

In the absense of restrictions, data is shown.

So you need to add a restriction for:

All individuals, "Immigration", "Show to members"

This will hide immigration facts from visitors.
