### ISSUE TITLE
memory issue when refreshing a page

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#12]
when refreshing 

http://www.jewishgen.org/webtrees/individual.php?pid=I155&ged=1_2738_RH_J_A_B.GED&theme=jewishgen

i get

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 261904 bytes) in \\192.168.254.206\JEWISHGEN\wwwroot\webtrees\vendor\bombayworks\zendframework1\library\Zend\Session\Abstract.php on line 287

is there a memory leak somewhere?

**Comment by fisharebest** [comment]
1) the page loads OK for me - no errors

2) there are some hidden comments at the end of the page which tell me that the page took 3.5 MB or memory to produce.

Are you seening this error consistently?  Were you logged in/out?

**Comment by mtobiasjg** [comment]
it occurs when logged in..... is it a problem with loading the menus? they only load when logged in.

**Comment by fisharebest** [comment]
> they only load when logged in

That's right.  I guessed you only want them suppressed for visitors, and that as an admin, you might want to use them to investigate issues, etc.

**Comment by fisharebest** [comment]
Fixed.  I'll send you an update shortly.
