### ISSUE TITLE
missing data when expanding individual on interactive chart

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#13]
when you click on a person in the chart and the box expands all data is lost (apart from name).  All dates/places are blank.

**Comment by fisharebest** [comment]
Which URL? Logged in/out?  If logged in, can you give me a login?

**Comment by mtobiasjg** [comment]
logged for sure....

see:

http://www.jewishgen.org/webtrees/individual.php?pid=I155&ged=1_2738_RH_J_A_B.GED&theme=jewishgen

the place names DO show but the years do not.

also you will see i got both headers top show - by copying the files into the webtrees directory.... but weirdly the footer page will not load though it is the same directory!!!  are you changing any paths after loading the main page?

**Comment by mtobiasjg** [comment]
logged OUT i meant.

**Comment by fisharebest** [comment]
> footer page will not load though it is the same directory!!! are you changing any paths after loading the main page?

Not explicitly, but we render the footer during the PHP shutdown phase, and PHP (especially apache) can modify the location.  The solution is to reference the file to a known location.  e.g.

`file_get_contents(__DIR__ . '/xxx.html')`

**Comment by fisharebest** [comment]
PS - raise a separate issue, rather than adding an "also".

Otherwise the bug report is likely to be closed when just one of them is resolved.

**Comment by fisharebest** [comment]
The missing date problem was in the core code - and is now fixed.
