### ISSUE TITLE
Creating a contact link containing substring of gedcom name and name of individual displayed

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#15]
you will see i now have some generic contact text in my title above the tree.....

how can i access the gedcom name and the name of the displayed individual to incorporate that data in my contact link?

**Comment by fisharebest** [comment]
Fixed.  There are now some variables created such as `$this->individual_name`, `$this->xref`, etc.

**Comment by mtobiasjg** [comment]
I tried using these (after downloading the latest version) but I am getting errors:

 

Notice: Undefined property: Fisharebest\Webtrees\JewishGenTheme::$individual_name in \\192.168.254.206\JEWISHGEN\wwwroot\webtrees\themes\jewishgen\theme.php on line 79 <file:///\\192.168.254.206\JEWISHGEN\wwwroot\webtrees\themes\jewishgen\theme.php%20on%20line%2079> 

 

M
