### ISSUE TITLE
remove popup when clicking on interactive tree title

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#17]
i am not sure what the popup is for on the interactive chart....

can  we remove it?

**Comment by fisharebest** [comment]
One of your initial requests was that you wanted this name to be a link back to your old site.

You haven't given me the URL format, so the popup is just a placeholder.

Are you saying that you no longer want this link back to your site?

**Comment by mtobiasjg** [comment]
Again I think there has been a misunderstanding. This probably refers to the contact link we wanted but we now have implemented that elsewhere in the display.

There is no need for the interactive tree title to be a link at all.

**Comment by fisharebest** [comment]
Fixed.  We send to you shortly
