### ISSUE TITLE
jewishgen breadcrumbs

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#18]
i see your latest theme tries to reset our breadcrumbs:

// Reset the page header, so that the automatic jewishgen.org breadcrumbs work

but it doesnt appear to be working....

My previous page (my own system search results) shows a breadcumb of:

Home » Databases » Family Tree of the Jewish People

and when displaying a record on the tree it really should say something like:

Home » Databases » Family Tree of the Jewish People » Joe Bloggs

and of course the links on the breadcrumb trail should still work....

Also the breadcrumb trail should be left aligned but it is now centred....

Any ideas?

**Comment by fisharebest** [comment]
Your breadcrumb script was picking up the `<title>` element from the `<head>`.

I simply tidied this up from "Joe Bloggs 1850-" to "Joe Bloggs".

> Also the breadcrumb trail should be left aligned but it is now centred....

I don't generate or format the breadcrumbs.  It is using the default alignment, which in the webtrees header is centered.

I've removed the centering.

**Comment by mtobiasjg** [comment]
I wonder why it is losing the full breadcrumb path….. ?

 

M

**Comment by fisharebest** [comment]
It is being generated by a javascript routine on your server.

I'd need to reverse-engineer it to find out how it works...

Greg

On 6 February 2015 at 13:15, mtobiasjg <notifications@github.com> wrote:

> I wonder why it is losing the full breadcrumb path….. ?
>
>
>
> M
>
>
>
> From: Greg Roach [mailto:notifications@github.com]
> Sent: 06 February 2015 12:50
> To: fisharebest/jg
> Cc: mtobiasjg
> Subject: Re: [jg] jewishgen breadcrumbs (#18)
>
>
>
> Your breadcrumb script was picking up the <title> element from the <head>.
>
> I simply tidied this up from "Joe Bloggs 1850-" to "Joe Bloggs".
>
> Also the breadcrumb trail should be left aligned but it is now centred....
>
> I don't generate or format the breadcrumbs. It is using the default
> alignment, which in the webtrees header is centered.
>
> I've removed the centering.
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/fisharebest/jg/issues/18#issuecomment-73231752> . <
> https://github.com/notifications/beacon/AKUbBkuXE4zq-s9VSUvdGwYnQLHkDw_Uks5npLABgaJpZM4Dcw2y.gif>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fisharebest/jg/issues/18#issuecomment-73234500>.
>



-- 
Greg Roach, Stony Stratford, Bucks, England, greg@subaqua.co.uk
"Don't eat animals - it's not good for them and they don't like it"

**Comment by fisharebest** [comment]
You'd need to add "names" for "folders" in your make-breadcrumb script:

http://www.jewishgen.org/JG/Scripts/Trail.js
