### ISSUE TITLE
colour of title bar is always blue....

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#19]
when loading individual.php for a female you can see the title bar starts as pink but then changes to blue - so currently both males and females (and presumably unknowns) all show as blue.

**Comment by fisharebest** [comment]
That's because the underlying theme (FAB) overwrites the colour with the same blue that is used for all tabs/accordions/etc.

You don't say whether you want

1) to retail the pink/blue for female/male
2) keep the "always blue", but avoid the FOUC
3) something else.

**Comment by mtobiasjg** [comment]
Sorry I thought it was a bug.

I think I would prefer sex-based colours, so pink for females, blue for males and white? for unknown.....


Michael 

Sent from my android device.

-----Original Message-----

**Comment by fisharebest** [comment]
Fixed.  Will send to you shortly.
