### ISSUE TITLE
Silhouettes

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#20]
where are these pngs stored and how can I change the images to use?

i dont see any images in our theme directory

**Comment by fisharebest** [comment]
This behaviour is inherited from the parent theme - and so it is using the FabTheme's images.

You can override it with the `parameters()` function.

**Comment by mtobiasjg** [comment]
ah ok. how and where do i use parameters() ?

**Comment by fisharebest** [comment]
Patience.  I can/will send you updates for all these sorts of issue, but not after every email...

**Comment by mtobiasjg** [comment]
no problem....

**Comment by fisharebest** [comment]
Simpe answer - copy the relevant CSS/image from the core theme to your custom theme and modify.  I'll send this to you shortly.
