### ISSUE TITLE
gedcom date

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#22]
Do you store the date of the gedcom as defined in the gedcom header?  I cant find it in the SQL database anywhere....

**Comment by fisharebest** [comment]
No, but we store the header.  Lots of ways to retrieve it.

What do you want.  The raw GEDCOM header, or a formatted date.

**Comment by mtobiasjg** [comment]
In this case I need to access it in the MySQL database.  What table / field is it stored in?

**Comment by fisharebest** [comment]
The raw GEDCOM record is in wt_other
