### ISSUE TITLE
bulk import

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#23]
testing this more.... and it is very slow.

i wonder if there are configuration settings on our MySQL server that could be tweaked to improve performance....

I am trying to import 200 gedcoms and I deleted a different 200 gedcoms from the data directory....  It is well over 1 hour so far and although all the new files have finally been imported only a few of the old deleted ones have disappeared from the panel.

What pages should i refresh to see any more progress - or should i not have to refresh any pages at all?

Should i have to press the bulk import button again??

**Comment by fisharebest** [comment]
> i wonder if there are configuration settings on our MySQL server that could be tweaked to improve performance....

Almost certainly.  If you are using the default / out-of-the-box config, then it can definitely be improved.

Database management is one of the things I do for a living.  I wrote an article on the wiki which you might find helpful.  http://wiki.webtrees.net/en/MySQL_Configuration

> Should i have to press the bulk import button again??

There are two phases.

In the first (after you click the submit button), the GEDCOM data is transfered (unprocessed) into temporary holding tables (wt_gedcom_chunk) as quickly as possible.  This is designed to work within various server limits, such as the largest block of data that can be passed to MySQL in one statement.

In the second phase, data is processed, indexed, validated, etc., and inserted into the genealogy data tables.  This happens in a slow, controlled, measured way - with progress bars etc.  There are typically 8 parallel loading processes taking place.  When one finishes, another starts.  You can press "F5" here if you wish (it will do no harm), but it should not be necessary.  Just wait until all the progress bars have reached 100%.

> Should i have to press the bulk import button again??

If phase 1 timed out, then navigate back to the page and wait for the files to finish importing.
Then you can run the import again, to pick up any remaining files.

If phase 1 did not time out, then no.

**Comment by mtobiasjg** [comment]
thanks.

will it do any harm if we re-submit?

i assume if/when we have 5500 files in the data folder and add a few more the update skips over the existing files very quickly as it compares the file datestamps? or does it do something different?

**Comment by fisharebest** [comment]
Correct - it records the timestamp of the file, and only imports it if the timestamp has changed.
