### ISSUE TITLE
menus not working

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#24]
really weird now....

whenever i login the system takes me to:

http://www.jewishgen.org/webtrees/admin_trees_manage.php

and clicking on any link brings me back to the same page.....

i cant load any other admin page.

**Comment by mtobiasjg** [comment]
when i try login under a different username (also an administration user) i get the error:

Fatal error: Call to a member function getPreference() on a non-object in \\192.168.254.206\JEWISHGEN\wwwroot\webtrees\app\Theme\BaseTheme.php on line 1493

**Comment by fisharebest** [comment]
Can you confirm that you are using the latest version of the code.  There have been many updates in the last 24 hours that could have caused/fixed this problem.

**Comment by mtobiasjg** [comment]
I am about to download again…..

 

M

**Comment by mtobiasjg** [comment]
nope we have major issues here.....

code updated and still same problem....

trying to load admin.php or any other admin page simply loads the admin_trees_manage.php page.

could we have corruption in our MySQL database???

**Comment by mtobiasjg** [comment]
i had loaded 200+ trees with 1.1M records.... should that make a difference?

As I said earlier the SQL load was bloody slow and I had to keep refreshing the bulk update....

EVERYTHING - even individual.php - is redirecting to admin_trees_manage.php

**Comment by mtobiasjg** [comment]
it is sorted.... but i have no idea how/why.....

**Comment by fisharebest** [comment]
If there are no (imported) trees, then you will be redirected to the admin_trees_manage page to create one.

Perhaps all your trees were in the middle of importing?
