### ISSUE TITLE
help with SQL view or a new table?

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#25]
Hi Greg

As you know we are planning on using webtrees to store our trees but then import the data into a separate database where searches will take place and link back to individual.php to display the interactive trees.

I am not a SQL programmer but I put together various VIEWS in SQL to access the data I needed from your tables.  I then import data from the view.

The view was complicated and I had to build it up over time from multiple more simple views. Performance was slow, but it worked, but as I add more and more data it is getting slower and slower and now with 1.1 million records it is really poor....

Would you be willing to see if you can come up with a more efficient SQL view?  If views wont work then another possibility is that we add a new SQL TABLE for our use - but of course that needs major changes to your core.

The data I need is:
SURNAME
GIVENNAME
ID (so I can generate the correct individual.php link)
GEDCOM  (so I can generate the correct individual.php link)
FATHER SURNAME
FATHER GIVENNAME
MOTHER SURNAME
MOTHER GIVENNAME
SPOUSE SURNAME
SPOUSE GIVENNAME
ALL PLACES LISTED AGAINST INDIVIDUAL (in particular B M an D)
BIRTH YEAR
MARRIAGE YEAR
DEATH YEAR
GEDCOM DATE

If a person has nicknames or alternate names or surnames they should be concatenated into the one field with a delimiter (probably / ) - this applies to givennames and surnames and for the individual, father,mother and spouse

There should only be one record for each individual, but if they married n times then there should be n rows, 1 for each different spouse, where all the information will be identical apart from the spouse names.

Is this something you could help with?

If a view is always going to be slow the other alternative would be to create a new table and store this data as gedcoms are imported and processed - if you think that would be possible.

**Comment by mtobiasjg** [comment]
it looks like my SQL view has finally reached its limit.... the view is taking too long to run when running against 2M records and I think MySQL is timing out. Have you had a chance to consider this?

**Comment by fisharebest** [comment]
> Would you be willing to see if you can come up with a more efficient SQL view?

I'm sure I can do this.  Probably take me an hour.

**Comment by mtobiasjg** [comment]
That would be great Greg. My problem with speed has been caused by using group_concat to remove duplicate individuals from the view by merging all name variations, date variations, father variations, mother variations into single fields delimited with ","

Not bothering with group_concat gives a reasonably fast view but there are far too many variants.

**Comment by mtobiasjg** [comment]
Hi Greg,

Any idea when you would be able to look into this?

Obviously we will pay extra for the time you devote to this.

Thanks

M 
PS I HOPE to be flying to the USA tomorrow to meet up with colleagues to discuss this and other developments - snow in the NE of the USA permitting!

**Comment by mtobiasjg** [comment]
how do i find the places of birth and death in your SQL tables? I can see the placelinks and places tables but neither tells you which EVENT the places are associated with.... clearly for marriages i can look up the family number but i cant see what to do for births and deaths.....

**Comment by fisharebest** [comment]
> how do i find the places of birth and death in your SQL tables?

Not possible via SQL.  The data model does not currently support it.  You'd need to process the data in PHP using the webtrees core functions to do this.

> Any idea when you would be able to look into this?

I wrote an initial query last night, but I only had 66000 individuals in the database on my laptop.  I didn't get time to generate a large dataset for any performance testing/tuning.  I planned to do this tonight.

The query does everything you asked for, except that (currently) the places for the individual facts (including birth/death) are in one column, and the family facts (including marriage) are in another.  Concatenating these gives duplicate place names.  These can no-doubt be eliminated by a union somewhere....

**Comment by mtobiasjg** [comment]
Thats great thanks. If you want me to see if your query runs in reasonable time with 2M records let me have copy!

How can php determine places of birth and death if they are not explicitly in the sql tables?

M

Sent from my android device.

-----Original Message-----

**Comment by fisharebest** [comment]
> How can php determine places of birth and death if they are not explicitly in the sql tables?

The data is stored in GEDCOM format.  The date/place tables are simply used as an index to allow the individual/family/etc. records to be found quickly.  It is held in the wt_individuals and wt_families tables.

PHP would parse the GEDCOM record for each individual, merge in any changes from pending edits, apply any privacy filtering, and then create an array of `Fact` objects, each of which contains an optional `Date` and `Place` object.

Whilst a structured database would be nice (!), user's data is in unstructured GEDCOM format.  We need the versioning/pending edit system, and it is non-trivial to implement this on highly structured data.

**Comment by mtobiasjg** [comment]
gotcha....

i also spotted in some of our data that there can be multiple DATE TAGS for the same event (where perhaps the data for birth date has come from several sources that contradict each other). I really need them group_concat'd just like name variations... so that I have a single record for every individual, only duplicated for multiple spouses....

**Comment by mtobiasjg** [comment]
Hi Greg

Any progress with this?

**Comment by mtobiasjg** [comment]
i really need to progress this.

it seems like my views are too slow and you say that generating a table is slow too (even on your setup which is running faster than ours).

What about my earlier idea of configuring the data import routine to have an optional 'create summary table'?  Would it be easier to populate the table during import?  It would probably not add too much runtime to each tree import and clearly on tree deletion the table would need updated too.

Although it would even more time to our initial data load of 5600 trees, ongoing it should be fine for updating a few dozen trees at a time, and the table would then be available for our secondary system to grab data from.

Is this a doable option Greg? Or is it too complicated doing this at tree import time?

**Comment by fisharebest** [comment]
Script sent to you
