### ISSUE TITLE
default theme

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#28]
how do i set the default theme for all/each tree?

i see on the admin pages you can set a default theme for a tree but when i click on the dropdown list for default theme there are no themes listed so i cannot select jewishgen.

**Comment by mtobiasjg** [comment]
for the moment I updated the webtrees1.wt15_gedcom_setting `setting_name`='THEME_DIR' to 'jewishgen'.

I THINK that is what I needed.....

**Comment by fisharebest** [comment]
That was unnessary.  If left blank, each tree will use the site's setting. (Control panel -> website preferencs)

So, set it once for the site - or every time for each tree.

**Comment by mtobiasjg** [comment]
gotcha
