### ISSUE TITLE
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\x931930\x0A...' for column 'i_gedcom' at row 1

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#3]
another SQL error on import. is this an encoding problem?

**Comment by fisharebest** [comment]
Can you let me have the file, so I can try to reproduce it locally.

**Comment by fisharebest** [comment]
You sent two files with similar (but not identical) error messages.

These are both files with "1 CHAR ANSI" headers, but are actually encoded with some other encoding.

x93 isn't used by most of the common encodings, and I don't recognise it out of context.
