### ISSUE TITLE
interactive trees on tabets

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#30]
more and more systems are running on tablets these days and i just tried the interactive trees on my tablet (andriod) on 4 different web browsers and they dont function 100%. the basic tree looks good and the boxes expand and close but there is no crosshair popup to move the tree around the page to see other branches.

is this a known problem / issue?

**Comment by fisharebest** [comment]
> is this a known problem / issue?

It is an old module, written before touch interfaces became common.

https://bugs.launchpad.net/webtrees/+bug/1101936

**Comment by mtobiasjg** [comment]
Ok. I see a user found a workaround using a 3rd part call. I might investigate that. There 2as a mention of webtrees possibly handling it if other external libraries were updated.

Is this anywhere on the radar?

M
PS on my tablet I have full mouse functionality so I was not expecting touch control. But the mouse doesn't work.....

Sent from my android device.

-----Original Message-----

**Comment by mtobiasjg** [comment]
that workaround was over 2 years ago.... i think there is a newer version of the hacked js that works with the latest jquery.

but your code appears to have changed a lot since then - i only see references in session.php. any ideas?

**Comment by fisharebest** [comment]
A fix has committed.
