### ISSUE TITLE
default theme

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#31]
how do you set the default theme for guests?

my website default theme is jewishgen but the first theme to show is webtrees when i use a new computer/browser.

**Comment by fisharebest** [comment]
Unless otherwise specified, trees use the theme set at the site level.  You set it using:

Control-panel, website, website settings, theme

Have you set this?

**Comment by mtobiasjg** [comment]
YES. I set that ages ago. But according to the docs the user and tree settings override that.

At tree level there is an option to set the theme but when I look at that for any tree there are no themes shown in the dropdown.

M

**Comment by fisharebest** [comment]
> there are no themes shown in the dropdown.

Are you saying that no trees are listed at all - or that they are set to "<default>"?

> the first theme to show is webtrees when i use a new computer/browser.

When logged in?  Have you set a theme for your user account?

**Comment by mtobiasjg** [comment]
All trees are set to default theme but the dropdown is empty. 

Our trees are open to visitors. We want our theme allways.




Sent from my android device.

-----Original Message-----

**Comment by mtobiasjg** [comment]
still kaput

all individual displays are using webtrees theme even though the site default is jewishgen.

and when switching to jewishgen theme females still show as title bar blue....

**Comment by fisharebest** [comment]
> there are no themes shown in the dropdown.

Fixed in the latest webtrees code.

**Comment by mtobiasjg** [comment]
Thanks

 

But does this solve our problem of a new computer/browser always using the webtrees theme by default?

 

M

**Comment by fisharebest** [comment]
> But does this solve our problem of a new computer/browser always using the webtrees theme by default?

I'm out of guesses.  Any chance I could actually take a look at your sytem?

**Comment by mtobiasjg** [comment]
Not easily….

 

Try it yourself:

 

http://testdata.jewishgen.org/databases/ftjp.htm

 

The webtrees config is set to jewishgen theme…. But you then allow that to be overwritten at tree and user level… we don’t want it overwritten – how do we ensure that all new gedcom imports are imported with the theme set to jewishgen?

 

M

**Comment by mtobiasjg** [comment]
I am trying to add you as an admin user so you can look at the system….

 

The admin pages are TOO SLOW!!!!

 

Your main admin page , though it looks basic actually has all the trees hidden in the background so takes forever to load.  Similarly when trying to add a user it loads and lists EVERY TREE!!!!!!  Surely there must be a better way?? My browser is hanging as it cannot display the full page.

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 10:28
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Not easily….

 

Try it yourself:

 

http://testdata.jewishgen.org/databases/ftjp.htm

 

The webtrees config is set to jewishgen theme…. But you then allow that to be overwritten at tree and user level… we don’t want it overwritten – how do we ensure that all new gedcom imports are imported with the theme set to jewishgen?

 

M

**Comment by fisharebest** [comment]
> Your main admin page , though it looks basic actually has all the trees hidden in the background so takes forever to load.

Define "forever".  On my laptop (running both client and server), it takes 20 seconds for a site with 5000 trees.

According to firebug, it takes 11 seconds to receive 6MB of data, then another 4 seconds to process/render it.

Expanding the list of trees takes 5.

**Comment by mtobiasjg** [comment]
You are not running a real-life test – everything is local to you.

 

My browser is HANGING trying to load the admin_user page.

 

M

**Comment by mtobiasjg** [comment]
Totally unusable now for me…. Sorry. I cant do anything in the admin pages.

 

M

**Comment by mtobiasjg** [comment]
This was very slow but usable (just) before your last update….

 

I have tried 4 different browsers and they are hanging, complaining about a long running script.

 

Can we PLEASE have admin pages that do not un-necessarily load every tree?????

 

I don’t need to see trees when adding users.

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 10:56
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Totally unusable now for me…. Sorry. I cant do anything in the admin pages.

 

M

**Comment by fisharebest** [comment]
Loading the "create new user" page takes about 65 seconds to render.

Yes, this is slow but surely not "unusable".

**Comment by fisharebest** [comment]
What browser are you using?  Some are much better than others...

**Comment by mtobiasjg** [comment]
I have tried

 

IE

Firefox

Opera

Chrome

 

ALL hang before the page has completely loaded/displayed.

 

M

**Comment by mtobiasjg** [comment]
Ok loaded and testing…. I have also made some changes (minor) to replaced NULLs and @N.N etc…..

 

The table does not seem to be picking up self_places. They are all blank….  Is there an error in that logic?

 

Speed is between 80000 and 300000 per hour but only a few tests done so far.

 

M

**Comment by fisharebest** [comment]
On 24 February 2015 at 17:34, mtobiasjg <notifications@github.com> wrote:
> The table does not seem to be picking up self_places. They are all blank…. Is there an error in that logic?

Quite possibly.  I was more keen to test the "difficult" logic, like
spouses and parents, etc.  I'll take a look.

Greg

> Speed is between 80000 and 300000 per hour but only a few tests done so far.

My laptop has a solid-state disk, which probably helps ;-)

Greg
--
Greg Roach, Stony Stratford, Bucks, England, greg@subaqua.co.uk
"Don't eat animals - it's not good for them and they don't like it"

**Comment by mtobiasjg** [comment]
Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M

**Comment by mtobiasjg** [comment]
I have the query duration displaying.

 

But a few other problems.


I got a “Row n was cut by GROUP_CONCAT()” error. I solved this by doing SET group_concat_max_len=15000;


Now I am getting:

 

Error Code: 1452 Cannot add or update a child row: a foreign key constraint fails (`webtrees1`.`wt15_gedcom_setting`, CONSTRAINT `wt15_gedcom_setting_ibfk_1` FOREIGN KEY (`gedcom_id`) REFERENCES `wt15_gedcom` (`gedcom_id`))

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 17:44
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M

**Comment by mtobiasjg** [comment]
Also getting some:

 

Error Code: 2014 Commands out of sync; you can't run this command now

 

Errors….. not sure why.

 

Any ideas?

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 21:10
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I have the query duration displaying.

 

But a few other problems.


I got a “Row n was cut by GROUP_CONCAT()” error. I solved this by doing SET group_concat_max_len=15000;


Now I am getting:

 

Error Code: 1452 Cannot add or update a child row: a foreign key constraint fails (`webtrees1`.`wt15_gedcom_setting`, CONSTRAINT `wt15_gedcom_setting_ibfk_1` FOREIGN KEY (`gedcom_id`) REFERENCES `wt15_gedcom` (`gedcom_id`))

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 17:44
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M

**Comment by mtobiasjg** [comment]
In jg_tmp_places

 

change

 

                WHERE i_file = p_gedcom_id

 

To

 

                WHERE i_file = p_file

 

M

**Comment by mtobiasjg** [comment]
Sorry my nonsense…..

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:20
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

In jg_tmp_places

 

change

 

                WHERE i_file = p_gedcom_id

 

To

 

                WHERE i_file = p_file

 

M

**Comment by mtobiasjg** [comment]
Your reference was to self_places instead of individual_places

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:27
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Sorry my nonsense…..

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:20
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

In jg_tmp_places

 

change

 

                WHERE i_file = p_gedcom_id

 

To

 

                WHERE i_file = p_file

 

M

**Comment by mtobiasjg** [comment]
I see some info online about sql queries / results needing stored or freed before you can process another – especially if one is slow…. But all the docs relate to php and NOT running SQ~L directly from the workbench…..

 

How do I fix this error?

 

The data is being imported ok but the script stops with the error….

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:02
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also getting some:

 

Error Code: 2014 Commands out of sync; you can't run this command now

 

Errors….. not sure why.

 

Any ideas?

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 21:10
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I have the query duration displaying.

 

But a few other problems.


I got a “Row n was cut by GROUP_CONCAT()” error. I solved this by doing SET group_concat_max_len=15000;


Now I am getting:

 

Error Code: 1452 Cannot add or update a child row: a foreign key constraint fails (`webtrees1`.`wt15_gedcom_setting`, CONSTRAINT `wt15_gedcom_setting_ibfk_1` FOREIGN KEY (`gedcom_id`) REFERENCES `wt15_gedcom` (`gedcom_id`))

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 17:44
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M

**Comment by mtobiasjg** [comment]
Also:

 

Error Code: 1062 Duplicate entry '2191-jg_export' for key 'PRIMARY'

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 00:41
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I see some info online about sql queries / results needing stored or freed before you can process another – especially if one is slow…. But all the docs relate to php and NOT running SQ~L directly from the workbench…..

 

How do I fix this error?

 

The data is being imported ok but the script stops with the error….

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:02
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also getting some:

 

Error Code: 2014 Commands out of sync; you can't run this command now

 

Errors….. not sure why.

 

Any ideas?

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 21:10
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I have the query duration displaying.

 

But a few other problems.


I got a “Row n was cut by GROUP_CONCAT()” error. I solved this by doing SET group_concat_max_len=15000;


Now I am getting:

 

Error Code: 1452 Cannot add or update a child row: a foreign key constraint fails (`webtrees1`.`wt15_gedcom_setting`, CONSTRAINT `wt15_gedcom_setting_ibfk_1` FOREIGN KEY (`gedcom_id`) REFERENCES `wt15_gedcom` (`gedcom_id`))

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 17:44
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M

**Comment by mtobiasjg** [comment]
Where exactly are these errors coming from?

 

It seems that MySQL is running the stored procedure and sometimes gets ahead of itself…. After sync errors I note that in the background MySQL appears to STILL be exporting further trees…. The number of records exported increases and more trees are marked as exported…. Thus when I restart it starts several trees further on from where the error was displayed…..

 

The sync errors are happening regularly – every few minutes!! I cannot easily process the entire database.

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 01:27
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also:

 

Error Code: 1062 Duplicate entry '2191-jg_export' for key 'PRIMARY'

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 00:41
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I see some info online about sql queries / results needing stored or freed before you can process another – especially if one is slow…. But all the docs relate to php and NOT running SQ~L directly from the workbench…..

 

How do I fix this error?

 

The data is being imported ok but the script stops with the error….

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:02
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also getting some:

 

Error Code: 2014 Commands out of sync; you can't run this command now

 

Errors….. not sure why.

 

Any ideas?

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 21:10
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I have the query duration displaying.

 

But a few other problems.


I got a “Row n was cut by GROUP_CONCAT()” error. I solved this by doing SET group_concat_max_len=15000;


Now I am getting:

 

Error Code: 1452 Cannot add or update a child row: a foreign key constraint fails (`webtrees1`.`wt15_gedcom_setting`, CONSTRAINT `wt15_gedcom_setting_ibfk_1` FOREIGN KEY (`gedcom_id`) REFERENCES `wt15_gedcom` (`gedcom_id`))

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 17:44
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M

**Comment by mtobiasjg** [comment]
I should add that when it runs it is FAST.  It is currently running on the smaller files (I loaded them last) and in the 55 seconds it ran between sync errors it added 30k records.  That equates to around 2 million per hour!

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 11:16
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Where exactly are these errors coming from?

 

It seems that MySQL is running the stored procedure and sometimes gets ahead of itself…. After sync errors I note that in the background MySQL appears to STILL be exporting further trees…. The number of records exported increases and more trees are marked as exported…. Thus when I restart it starts several trees further on from where the error was displayed…..

 

The sync errors are happening regularly – every few minutes!! I cannot easily process the entire database.

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 01:27
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also:

 

Error Code: 1062 Duplicate entry '2191-jg_export' for key 'PRIMARY'

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 00:41
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I see some info online about sql queries / results needing stored or freed before you can process another – especially if one is slow…. But all the docs relate to php and NOT running SQ~L directly from the workbench…..

 

How do I fix this error?

 

The data is being imported ok but the script stops with the error….

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:02
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also getting some:

 

Error Code: 2014 Commands out of sync; you can't run this command now

 

Errors….. not sure why.

 

Any ideas?

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 21:10
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I have the query duration displaying.

 

But a few other problems.


I got a “Row n was cut by GROUP_CONCAT()” error. I solved this by doing SET group_concat_max_len=15000;


Now I am getting:

 

Error Code: 1452 Cannot add or update a child row: a foreign key constraint fails (`webtrees1`.`wt15_gedcom_setting`, CONSTRAINT `wt15_gedcom_setting_ibfk_1` FOREIGN KEY (`gedcom_id`) REFERENCES `wt15_gedcom` (`gedcom_id`))

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 17:44
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M

**Comment by mtobiasjg** [comment]
Solved…..

 

If I comment out the stats messages, both before and after then it runs and doesn’t crash….. 18 minutes so far and looking good….

 

I might change the code to have the messages as an option based on a passed parameter.

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 11:21
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I should add that when it runs it is FAST.  It is currently running on the smaller files (I loaded them last) and in the 55 seconds it ran between sync errors it added 30k records.  That equates to around 2 million per hour!

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 11:16
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Where exactly are these errors coming from?

 

It seems that MySQL is running the stored procedure and sometimes gets ahead of itself…. After sync errors I note that in the background MySQL appears to STILL be exporting further trees…. The number of records exported increases and more trees are marked as exported…. Thus when I restart it starts several trees further on from where the error was displayed…..

 

The sync errors are happening regularly – every few minutes!! I cannot easily process the entire database.

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 01:27
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also:

 

Error Code: 1062 Duplicate entry '2191-jg_export' for key 'PRIMARY'

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 00:41
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I see some info online about sql queries / results needing stored or freed before you can process another – especially if one is slow…. But all the docs relate to php and NOT running SQ~L directly from the workbench…..

 

How do I fix this error?

 

The data is being imported ok but the script stops with the error….

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 22:02
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Also getting some:

 

Error Code: 2014 Commands out of sync; you can't run this command now

 

Errors….. not sure why.

 

Any ideas?

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 21:10
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

I have the query duration displaying.

 

But a few other problems.


I got a “Row n was cut by GROUP_CONCAT()” error. I solved this by doing SET group_concat_max_len=15000;


Now I am getting:

 

Error Code: 1452 Cannot add or update a child row: a foreign key constraint fails (`webtrees1`.`wt15_gedcom_setting`, CONSTRAINT `wt15_gedcom_setting_ibfk_1` FOREIGN KEY (`gedcom_id`) REFERENCES `wt15_gedcom` (`gedcom_id`))

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 24 February 2015 17:44
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] default theme (#31)

 

Another thought – could the final progress display show the time taken and records/minute or records/hour rate  - would be useful.

 

If that is possible let me know any changes required for that and where to put them given my other changes made….

 

M
