### ISSUE TITLE
jg_export

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#32]
Hi Greg

thought i should start a new issue

as you know things are going pretty well now... though it appears to be slowing down a little after doing 2million records in the first hour....

Clearly going forward run export_all will catch all new gedcoms added.... and I am happy to uncomment the code (already have) that checks for non-existent trees and deletes the data from the export table.

Our only remaining problem are trees we REPLACE.

updating a gedcom will delete it from the webtrees tables and import the new version. It will therefore result in a 'new' tree that appears as if it has not been exported before.

running export_all will now export the updated file but it will still have the original gedcom data in the table.  The only way to solve this is for us to remember to reset_tree the correct file.

This is a PAIN. Deletions are rare but updates are common.

Is there no way during a bulk sync you could offer us the option to call reset_tree for the replaced files? then we know that simply running export_all will produce a correct export table.

I know you dont like adding special case code for us but could this not be done by a special set of additional admin parameters./settings?

thanks

M

**Comment by mtobiasjg** [comment]
do you have any timeout issues when running such a long (hours) process?

i am having to remember to checkl the MySQL workbench timeout setitngs before running scripts like this.

Is there any way the stored procedures could set the timeout appropriately before running?

I have seen reference to SET SESSION MAX_STATEMENT_TIME but it appears to be needed to be added to EVERY MySQL command.....

**Comment by fisharebest** [comment]
> Our only remaining problem are trees we REPLACE.

I think there is a neat solution to this.

Currently the "exported" flag is just a yes/no.

We could easily change it to record the file version (i.e. the file modification time) that we use for the sync.

We'd then know if the export was made with the latest version of the file, and could remove/reimport it automatically.

You said you'd made changes to the script.  We can't both make edits independently, or some will get lost.  How do you want to proceed?  We could add the code to a github repository here, so we could both edit it?

> do you have any timeout issues when running such a long (hours) process?

No.  The MySQL command line prompt does not have timeout issues.  (If there is an inactivity timeout, it reconnects automatically).

If you're using a GUI client (e.g. MySQL Workbench), then it is the responsibility of your client to handle this.

Open up a DOS window.  Navigate to the MySQL folder (e.g. `cd C:\path\to\mysql\bin`), type `mysql --database=XXX --user=XXX --password=XXX` to start it up.  You can now either type commands directly (e.g. `CALL export_all;`) or run external files (e.g. `source path\to\file.sql`).

**Comment by mtobiasjg** [comment]
OK.

 

I don’t fully understand how you would implement this (everything so far has been based on the internal gedcom_ids rather than gedcom names…..). Will you have to store the gedcom process datetime in the jg_export table and compare the NAMES of files during the update?

 

As for the command line MyQSL access…. Ouch – I hate command line interfaces.

 

We want to EVENTUALLY open the admin of this system up to volunteers who will NOT be given access to MySQL.  They would perform webtrees bulk syncs and then we would love a web interface to call the export_all to update the jg_export table etc….

 

As for the stored procedures, I had to split them up in MySQL to get it to save them properly…

 

I am happy to send you a file of the current versions for GitHub.

 

M

**Comment by mtobiasjg** [comment]
The call from the workbench timed out again but it appears the script IS still running on the server….

 

After 4 hours it had exported 5.2M records and is proceeding. I wrote a small php script to monitor the progress…..

 

M

**Comment by fisharebest** [comment]
> The call from the workbench timed out again but it appears the script IS still running on the server….

If MySQL workbench (which I have never used) does this, then please be careful not to run the script twice at the same time.  You may end up with duplicated data inserted into the export table...

**Comment by mtobiasjg** [comment]
I just copy/pasted the 4 procedures into the attached file…..

 

M

 

From: Michael Tobias [mailto:mtobias@tobias.org.uk] 
Sent: 25 February 2015 15:58
To: 'fisharebest/jg'; 'fisharebest/jg'
Cc: 'mtobiasjg'
Subject: RE: [jg] jg_export (#32)

 

OK.

 

I don’t fully understand how you would implement this (everything so far has been based on the internal gedcom_ids rather than gedcom names…..). Will you have to store the gedcom process datetime in the jg_export table and compare the NAMES of files during the update?

 

As for the command line MyQSL access…. Ouch – I hate command line interfaces.

 

We want to EVENTUALLY open the admin of this system up to volunteers who will NOT be given access to MySQL.  They would perform webtrees bulk syncs and then we would love a web interface to call the export_all to update the jg_export table etc….

 

As for the stored procedures, I had to split them up in MySQL to get it to save them properly…

 

I am happy to send you a file of the current versions for GitHub.

 

M

**Comment by mtobiasjg** [comment]
Yup, but it is good to know that I could kick it off (once) via php and then call an auto-reloading page that monitors files/records processed….

 

M
