### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'n_sort' at row 1

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#4]
another SQL import error

**Comment by fisharebest** [comment]
You probably have an individual's name longer than 255 characters.

GEDCOM format only allows up to 120.

Probably garbage data.  I can add a check for this.

(Or, we can disable strict mode....  )

**Comment by fisharebest** [comment]
GEDCOM allows source names to be up to 248 characters.  One of yours was 309.  Fixed
