### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'HEAD-369' for key 'PRIMARY'

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#5]
i assume this an invalid duplicate entry in the gedcom file.

**Comment by fisharebest** [comment]
Yes.  It means you have two HEAD records.

**Comment by fisharebest** [comment]
This is an invalid file, and cannot be loaded.  If you need help fixing it, email it to me.
