### ISSUE TITLE
customised theme

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#7]
We want to brand the output to sync with our existing website.  Will it be possible for us to add code to INCLUDE header and footer files? (possibly more than one of each) ?  If that is not possible then we will simply add a simple header/logo but ideally we would like to add the headers/footers.  We also will need customised links based on the gedcom number (we might have to parse the gedcom filename to produce only the numeric code) and the name of main individual displayed. This will be a 'contact link' to contact the submitter but is not a 'mailto' but another script - likely php.  Can we have full control over the theme to add such links? (and we will need to know how to pick up the relevant details from the data records being displayed).

**Comment by fisharebest** [comment]
> Will it be possible for us to add code to INCLUDE header and footer files? (possibly more than one of each) 

Yes.  Do you want *any* of the header/footer to be generated by webtrees/the theme, or do you want to supply *all* of it from your include files?

> We also will need customised links based on the gedcom number (we might have to parse the gedcom filename to produce only the numeric code) and the name of main individual displayed.

Can you supply the details of the links.  Any example would help.  It is difficult to write this without knowing what it needs to do.

> This will be a 'contact link' to contact the submitter but is not a 'mailto' but another script - likely php.

You are supplying the footer file, so you can include anything you like

> we will need to know how to pick up the relevant details

Tell me what details you want, and I can tell you how to access them.

**Comment by mtobiasjg** [comment]
I thijnk we would prefer to handle all of the headers and footers ourselves.  If you have standard webtrees ones can you just leave them in the code but commented out?

We will need to re-write our contact script.  But it will almost certainly only need TWO items of information.

1. the name of the gedcom file - or rather the numeric code.  As long as we can pick up the gedcom name we can parse it to extract the code we need (eg extract 2345 from 1_2345_MT.GED)

2. the name of the primary individual in the display.

**Comment by fisharebest** [comment]
These are now available in the theme.
