### ISSUE TITLE
bulk import tests

### ISSUE THREAD

**Issue by mtobiasjg** [fisharebest/jg#9]
is there an easy way to WIPE all data from the system and start again?  We will be testing the bulk import on various files and I need a way to re-start from scratch.

Where imports have failed - eg ANSEL encoded - how do I easily remove all those trees from the control panel? Do I simply delete the files from the data folder? Not sure that works - that is when I got the errors when deleting the files and trying bulk import again.

Notice: Undefined index: in \\192.168.254.206\JEWISHGEN\wwwroot\webtrees\library\WT\Tree.php on line 287 Fatal error: Call to a member function getPreference() on a non-object in \\192.168.254.206\JEWISHGEN\wwwroot\webtrees\admin_trees_manage.php on line 109

Does the system continually scan the data folder and apply updates behind the scenes - or only when I select the bulk import and click.... ?

**Comment by fisharebest** [comment]
> Where imports have failed - eg ANSEL encoded - how do I easily remove all those trees from the control panel?

Delete the GEDCOM file from the data folder, and click the "bulk import" (actually a synchronise) button again.

That or replace the file with a converted one and do the same.



> Does the system continually scan the data folder and apply updates behind the scenes - or only when I select the bulk import and click.... ?

Only when you click.  The system is designed for websites with low timeouts, and is designed to pick up where it left off.  If your server can only load 250 gedcom files, and you have 1000 new/changed, then you may need to click the "bulk import" 4 times.

**Comment by fisharebest** [comment]
PS - the "failed" files are only shown on the admin page.  They are not visitble to end users.

**Comment by fisharebest** [comment]
I've tried to
(a) import an invalid file - which fails.

and then
(b) delete the file
or
(c) replace it with a valid file

and then re-run the bulk import.

Seems to work fine.  If you still have problems, let me have the details.
